// <auto-generated />
using FeatureToggle.NET.Store;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FeatureToggle.NET.Store.Migrations
{
    [DbContext(typeof(FeatureToggleDbContext))]
    partial class FeatureToggleContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("FeatureToggle.NET.Core.Types.Env", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("FriendlyName");

                    b.HasKey("Id");

                    b.ToTable("Environments");
                });

            modelBuilder.Entity("FeatureToggle.NET.Core.Types.FeatureValue", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Type");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("FeatureValues");
                });
#pragma warning restore 612, 618
        }
    }
}
