image: Visual Studio 2017

configuration: Release

before_build:
  - dotnet restore

build_script:
  - dotnet build .\FeatureToggle.NET.sln

test_script:
  - dotnet test .\FeatureToggle.NET.sln